import type { Metadata } from "next";

import { Montserrat } from "next/font/google";

import NavBar from "./_components/navBar";
import Header from "./_components/header";
import Footer from "./_components/footer";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"], // Add the weight property
  display: "swap",
});
export const metadata: Metadata = {
  title: {
    template: "s/ PsycoTena",
    default: "Welcome to TenaPsyco",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <NavBar />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
